CRCTABLE:		; Autogenerated by mkcrctable.awk
	DW F08DH
	DW Kyocera_Kyotronic_85_orig
	DW 64A8H
	DW Kyocera_Kyotronic_85_y2k
	DW A48DH
	DW NEC_PC_8201_A_orig
	DW 87F7H
	DW NEC_PC_8201_A_REX_y2k
	DW 8CA0H
	DW NEC_PC_8201_A_y2k
	DW 0508H
	DW NEC_PC_8201_Japan_orig
	DW 9FF5H
	DW NEC_PC_8300_orig
	DW E3A9H
	DW NEC_PC_8300_y2k
	DW 5DD2H
	DW Olivetti_M10_Eur_orig
	DW 1B13H
	DW Olivetti_M10_Eur_y2k
	DW 5D9FH
	DW Olivetti_M10_North_America_orig
	DW 5E44H
	DW Olivetti_M10_North_America_y2k
	DW 870FH
	DW Tandy_102_REX_y2k
	DW 5CF0H
	DW Tandy_102_uk_orig
	DW 9EC4H
	DW Tandy_102_uk_y2k
	DW 1C6FH
	DW Tandy_102_us_orig
	DW DE5BH
	DW Tandy_102_us_y2k
	DW 3D1AH
	DW Tandy_200_M13_orig
	DW B76FH
	DW Tandy_200_M13_REX
	DW 958CH
	DW Tandy_200_M14_orig
	DW 7C97H
	DW Tandy_200_M15_corrupt
	DW C061H
	DW Tandy_200_M15M13M14
	DW 9534H
	DW Tandy_200_M15M13M14_y2k
	DW 9535H
	DW Tandy_200_M15_orig
	DW 25C3H
	DW Tandy_200_M15_REX_corrupt
	DW 3EFFH
	DW Tandy_200_M15_REX_y2k
	DW 67ABH
	DW Tandy_200_M15_y2k
	DW 2A64H
	DW Televerket_Modell_100_orig
	DW 60F0H
	DW TRS_80_Model_100_LibROM_1_1a
	DW 34F5H
	DW TRS_80_Model_100_orig
	DW AF95H
	DW TRS_80_Model_100_REX_y2k
	DW 7A77H
	DW TRS_80_Model_100_uk_skl
	DW A010H
	DW TRS_80_Model_100_uk_y2k
	DW 6224H
	DW TRS_80_Model_100_us_26_3802B
	DW F6C1H
	DW TRS_80_Model_100_y2k
	DW E71CH
	DW Kyocera_Kyotronic_85_VirT_1_7_no_Y2K
	DW 554DH
	DW TRS_80_Model_100_VirT_1_7
	DW 7DD7H
	DW Tandy_102_US_VirT_1_7
	DW 3E00H
	DW Tandy_200_VirT_1_7
	DW 91C7H
	DW NEC_PC_8201A_VirT_1_7
	DW D4BAH
	DW NEC_PC_8300_VirT_1_7
	DW B753H
	DW Olivetti_M10_Europe_VirT_1_7
	DW 0000H
	DW ROM_NOT_RECOGNIZED
Kyocera_Kyotronic_85_VirT_1_7_no_Y2K:    DB "VirT 1.7, no Y2K",0
Kyocera_Kyotronic_85_orig:               DB "",0
Kyocera_Kyotronic_85_y2k:                DB "y2k",0
NEC_PC_8201A_VirT_1_7:                   DB "VirT 1.7",0
NEC_PC_8201_A_REX_y2k:                   DB "A REX y2k",0
NEC_PC_8201_A_orig:                      DB "A",0
NEC_PC_8201_A_y2k:                       DB "A y2k",0
NEC_PC_8201_Japan_orig:                  DB "Japan",0
NEC_PC_8300_VirT_1_7:                    DB "VirT 1.7",0
NEC_PC_8300_orig:                        DB "",0
NEC_PC_8300_y2k:                         DB "y2k",0
Olivetti_M10_Eur_orig:                   DB "",0
Olivetti_M10_Eur_y2k:                    DB "y2k",0
Olivetti_M10_Europe_VirT_1_7:            DB "VirT 1.7",0
Olivetti_M10_North_America_orig:         DB "",0
Olivetti_M10_North_America_y2k:          DB "y2k",0
TRS_80_Model_100_LibROM_1_1a:            DB "LibROM-1.1a",0
TRS_80_Model_100_REX_y2k:                DB "REX y2k",0
TRS_80_Model_100_VirT_1_7:               DB "VirT 1.7",0
TRS_80_Model_100_orig:                   DB "",0
TRS_80_Model_100_uk_skl:                 DB "skl",0
TRS_80_Model_100_uk_y2k:                 DB "y2k",0
TRS_80_Model_100_us_26_3802B:            DB "26-3802B",0
TRS_80_Model_100_y2k:                    DB "y2k",0
Tandy_102_REX_y2k:                       DB "REX y2k",0
Tandy_102_US_VirT_1_7:                   DB "VirT 1.7",0
Tandy_102_uk_orig:                       DB "",0
Tandy_102_uk_y2k:                        DB "y2k",0
Tandy_102_us_orig:                       DB "",0
Tandy_102_us_y2k:                        DB "y2k",0
Tandy_200_M13_REX:                       DB "M13 REX",0
Tandy_200_M13_orig:                      DB "M13",0
Tandy_200_M14_orig:                      DB "M14",0
Tandy_200_M15M13M14:                     DB "M15M13M14",0
Tandy_200_M15M13M14_y2k:                 DB "M15M13M14 y2k",0
Tandy_200_M15_REX_corrupt:               DB "M15 REX corrupt",0
Tandy_200_M15_REX_y2k:                   DB "M15 REX y2k",0
Tandy_200_M15_corrupt:                   DB "M15 corrupt",0
Tandy_200_M15_orig:                      DB "M15",0
Tandy_200_M15_y2k:                       DB "M15 y2k",0
Tandy_200_VirT_1_7:                      DB "VirT 1.7",0
Televerket_Modell_100_orig:              DB "",0
ROM_NOT_RECOGNIZED:                      DB "Unknown!\r\n! Please file an issue at\r\n! github.com/hackerb9/crc16-modelt\r\n",0
