CRCTABLE:		; Autogenerated by mkcrctable.awk
	DW 70C3H
	DW HD61830_lcd
	DW F08DH
	DW Kyocera_Kyotronic_85_orig
	DW 64A8H
	DW Kyocera_Kyotronic_85_y2k
	DW A48DH
	DW NEC_PC_8201A_orig
	DW 8CA0H
	DW NEC_PC_8201A_y2k
	DW 4793H
	DW NEC_PC_8300_Beckman_E3_2_orig
	DW 9FF5H
	DW NEC_PC_8300_orig
	DW E3A9H
	DW NEC_PC_8300_y2k
	DW 5DD2H
	DW Olivetti_M10_Eur_orig
	DW 1B13H
	DW Olivetti_M10_Eur_y2k
	DW 5D9FH
	DW Olivetti_M10_North_America_orig
	DW 5E44H
	DW Olivetti_M10_North_America_y2k
	DW 5CF0H
	DW Tandy_102_uk_orig
	DW 9EC4H
	DW Tandy_102_uk_y2k
	DW 1C6FH
	DW Tandy_102_us_orig
	DW DE5BH
	DW Tandy_102_us_y2k
	DW 3D1AH
	DW Tandy_200_M13_orig
	DW 958CH
	DW Tandy_200_M14_orig
	DW 25C3H
	DW Tandy_200_M15_orig
	DW 67ABH
	DW Tandy_200_M15_y2k
	DW 9534H
	DW Tandy_200_us_orig
	DW A2B3H
	DW Tandy_600_BASIC
	DW 2A64H
	DW Televerket_Modell_100_orig
	DW 60F0H
	DW TRS_80_Model_100_LibROM_1_1a
	DW 34F5H
	DW TRS_80_Model_100_orig
	DW 7A77H
	DW TRS_80_Model_100_uk_skl
	DW A010H
	DW TRS_80_Model_100_uk_y2k
	DW 6224H
	DW TRS_80_Model_100_us_26_3802B
	DW F6C1H
	DW TRS_80_Model_100_y2k
	DW E71CH
	DW Kyocera_Kyotronic_85_VirT_1_7_no_Y2K
	DW 554DH
	DW TRS_80_Model_100_VirT_1_7
	DW 7DD7H
	DW Tandy_102_US_VirT_1_7
	DW 0665H
	DW Tandy_200_VirT_1_7
	DW 91C7H
	DW NEC_PC_8201A_VirT_1_7
	DW D4BAH
	DW NEC_PC_8300_VirT_1_7
	DW B753H
	DW Olivetti_M10_Europe_VirT_1_7
	DW 0000H
	DW ROM_NOT_RECOGNIZED
HD61830_lcd:                             DB "lcd",0
Kyocera_Kyotronic_85_VirT_1_7_no_Y2K:    DB "VirT 1.7, no Y2K",0
Kyocera_Kyotronic_85_orig:               DB "",0
Kyocera_Kyotronic_85_y2k:                DB "y2k",0
NEC_PC_8201A_VirT_1_7:                   DB "VirT 1.7",0
NEC_PC_8201A_orig:                       DB "",0
NEC_PC_8201A_y2k:                        DB "y2k",0
NEC_PC_8300_Beckman_E3_2_orig:           DB "",0
NEC_PC_8300_VirT_1_7:                    DB "VirT 1.7",0
NEC_PC_8300_orig:                        DB "",0
NEC_PC_8300_y2k:                         DB "y2k",0
Olivetti_M10_Eur_orig:                   DB "",0
Olivetti_M10_Eur_y2k:                    DB "y2k",0
Olivetti_M10_Europe_VirT_1_7:            DB "VirT 1.7",0
Olivetti_M10_North_America_orig:         DB "",0
Olivetti_M10_North_America_y2k:          DB "y2k",0
TRS_80_Model_100_LibROM_1_1a:            DB "LibROM-1.1a",0
TRS_80_Model_100_VirT_1_7:               DB "VirT 1.7",0
TRS_80_Model_100_orig:                   DB "",0
TRS_80_Model_100_uk_skl:                 DB "skl",0
TRS_80_Model_100_uk_y2k:                 DB "y2k",0
TRS_80_Model_100_us_26_3802B:            DB "26-3802B",0
TRS_80_Model_100_y2k:                    DB "y2k",0
Tandy_102_US_VirT_1_7:                   DB "VirT 1.7",0
Tandy_102_uk_orig:                       DB "",0
Tandy_102_uk_y2k:                        DB "y2k",0
Tandy_102_us_orig:                       DB "",0
Tandy_102_us_y2k:                        DB "y2k",0
Tandy_200_M13_orig:                      DB "M13",0
Tandy_200_M14_orig:                      DB "M14",0
Tandy_200_M15_orig:                      DB "M15",0
Tandy_200_M15_y2k:                       DB "M15.y2k",0
Tandy_200_VirT_1_7:                      DB "VirT 1.7",0
Tandy_200_us_orig:                       DB "us",0
Tandy_600_BASIC:                         DB "BASIC",0
Televerket_Modell_100_orig:              DB "",0
ROM_NOT_RECOGNIZED:                      DB "Unknown ROM. Please report at\r\ngithub.com/hackerb9/crc16-modelt",0
