#!/bin/bash
# -*- awk -*-

EXTRA=adjunct/extrasums.txt   # precalculated checksums to include even though we lack the ROMs.
(./crc16 ROMs/*; [ -r "$EXTRA" ] && cat "$EXTRA" ) | awk -v dq='"' '
BEGIN {
    print "CRCTABLE:		; Autogenerated by mkcrctable.awk";
}
{
    if (file[$1] != "") {
	printf("\aError! Two files have the same checksum: %s\n", $1) >"/dev/stderr";
	printf("\t%s\n", file[$1]) >"/dev/stderr";
	printf("\t%s\n", $2) >"/dev/stderr";
	exit(1);
    } else {
	file[$1] = $2;
    }
    # ROM Files are named MAKE_MODEL+VARIATION.bin.
    # For example, "ROMs/Kyocera_Kyotronic_85+y2k.bin"
    nm=$2;			# Remember filename for creating the printable name[].
    gsub(/^.*\//, "", $2);	# Ditch directory
    gsub(/.bin$/, "", $2);	# and the extension.
    gsub(/[^A-Za-z0-9]/, "_", $2); # Non-alphanumeric becomes underscore for the label.
    gsub(/_+/, "_", $2);	   # Smush underscores together.
    gsub(/^_|_$/, "", $2);	   # Remove leading and trailing underscores.
    gsub(/^ +| +$/, "", $2);	   # If any spaces are now on edges, remove those, too.
    label[$1]=$2;		   # Assign a valid identifier as a label for this filename.
    if (name[label[$1]] != "") {
	printf("\aError! Two files have the same identifier: %s\n", label[$1]) >"/dev/stderr";
	printf("\t%s\n", file[$1]) >"/dev/stderr";
	printf("\t%s\n", nm) >"/dev/stderr";
	exit(1);
    }
    # Keep only variant information which is between first plus and last period.
    if (gsub(/[^+]*\+/, "", nm) < 1) {
	printf("\aError! Filenames must have variant following plus sign.\n") >"/dev/stderr";
	printf("\tMissing \"+\" in %s\n", file[$1]) >"/dev/stderr";
	printf("\tExample: Tandy_200+us.orig.bin\n") >"/dev/stderr";
	exit(1);
    }
    gsub(/\.bin$/, "", nm);
    gsub(/_/, " ", nm);
    name[label[$1]] = dq nm dq;		# Save for defining labels later.
    print "\tDW " $1 "H";		# CRC value as 16-bits
    print "\tDW " label[$1];		# Address of label (also 16-bits)
}

ENDFILE {
    print "\tDW 0000H";
    print "\tDW ROM_NOT_RECOGNIZED"
    asort(label)
    for (i in label) {
	printf("%-40s DB %s,0\n", gensub(/$/, ":", "g", label[i]), name[label[i]]);
    }
    printf("%-40s DB " dq "%s" dq ",0\n", "ROM_NOT_RECOGNIZED:",
	   "Unknown ROM. Please report at\\r\\ngithub.com/hackerb9/crc16-modelt");
}
'
