#!/bin/bash
./crc16 ROMs/* |
awk -v dq='"' '
BEGIN {
    print "ROMTABLE:		; Autogenerated by mkromtable.awk";
}
{
    gsub(/^.*\//, "", $2);
    gsub(/.bin$/, "", $2);
    gsub(/.orig$/, "", $2);
    gsub(/[^A-Za-z0-9]/, "_", $2);
    gsub(/^_+|_+$/, "", $2);
    gsub(/_+/, "_", $2);
    if (ident[$1] != "") {
	printf("\aError! Two files have the same checksum: %s\n", $1) >"/dev/stderr";
	exit(1);
    }
    ident[$1]=$2;
    if (name[ident[$1]] != "") {
	printf("\aError! Two files have the same identifier: %s\n", ident[$1]) >"/dev/stderr";
	exit(1);
    }
    gsub(/_/, " ", $2);
    name[ident[$1]] = dq $2 dq;
    print "\tDW " $1 "H";
    print "\tDW " ident[$1];
}

ENDFILE {
    asort(ident)
    for (i in ident) {
	printf("%-40s DB %s,0\n", gensub(/$/, ":", "g", ident[i]), name[ident[i]])
    }
}
'
