#!/bin/bash
# -*- awk -*-

EXTRA=adjunct/extrasums.txt   # precalculated checksums to include even though we lack the ROMs.
(./crc16 ROMs/*; [ -r "$EXTRA" ] && cat "$EXTRA" ) | awk -v dq='"' '
BEGIN {
    print "ROMTABLE:		; Autogenerated by mkromtable.awk";
}
{
    if (file[$1] != "") {
	printf("\aError! Two files have the same checksum: %s\n", $1) >"/dev/stderr";
	printf("\t%s\n", file[$1]) >"/dev/stderr";
	printf("\t%s\n", $2) >"/dev/stderr";
	exit(1);
    } else {
	file[$1] = $2;
    }
    gsub(/^.*\//, "", $2);
    gsub(/.bin$/, "", $2);
    gsub(/.orig$/, "", $2);
    gsub(/^ +| +$/, "", $2);
    nm=$2;
    gsub(/[^A-Za-z0-9]/, "_", $2);
    gsub(/_+/, "_", $2);
    ident[$1]=$2;
    if (name[ident[$1]] != "") {
	printf("\aError! Two files have the same identifier: %s\n", ident[$1]) >"/dev/stderr";
	exit(1);
    }
    gsub(/_/, " ", nm);
    name[ident[$1]] = dq nm dq;
    print "\tDW " $1 "H";
    print "\tDW " ident[$1];
}

ENDFILE {
    print "\tDW 0000H";
    print "\tDW ROM_NOT_RECOGNIZED"
    asort(ident)
    for (i in ident) {
	printf("%-40s DB %s,0\n", gensub(/$/, ":", "g", ident[i]), name[ident[i]]);
    }
    printf("%-40s DB " dq "%s" dq ",0\n", "ROM_NOT_RECOGNIZED",
	   "ROM not recognized. Please report at\\r\\ngithub.com/hackerb9/crc16-modelt");
}
'
