ROMTABLE:		; Autogenerated by mkromtable.awk
	DW 70C3H
	DW hd61830
	DW F08DH
	DW Kyocera_Kyotronic_85
	DW 64A8H
	DW Kyocera_Kyotronic_85_y2k
	DW 5DD2H
	DW M10_System_ROM_EU
	DW 1B13H
	DW M10_System_ROM_EU_y2k
	DW 5D9FH
	DW M10_System_ROM_NorthAmerica
	DW 5E44H
	DW M10_System_ROM_NorthAmerica_y2k
	DW A48DH
	DW NEC_PC_8201A
	DW 8CA0H
	DW NEC_PC_8201A_y2k
	DW 4793H
	DW NEC_PC_8300_Beckman_E3_2
	DW 9FF5H
	DW NEC_PC_8300
	DW E3A9H
	DW NEC_PC_8300_y2k
	DW 5CF0H
	DW Tandy_102_uk
	DW 9EC4H
	DW Tandy_102_uk_y2k
	DW 1C6FH
	DW Tandy_102_us
	DW DE5BH
	DW Tandy_102_us_y2k
	DW 3D1AH
	DW Tandy_200_M13
	DW 958CH
	DW Tandy_200_M14
	DW 25C3H
	DW Tandy_200_M15
	DW 67ABH
	DW Tandy_200_M15_y2k
	DW 9534H
	DW Tandy_200_us
	DW A2B3H
	DW Tandy_600_BASIC
	DW 2A64H
	DW Televerket_Modell_100
	DW 34F5H
	DW TRS_80_Model_100
	DW F6C1H
	DW TRS_80_Model_100_y2k
	DW E71CH
	DW Kyocera_Kyotronic_85_Virtual_T_1_7_no_Y2K
	DW 554DH
	DW TRS_80_Model_100_Virtual_T_1_7
	DW 7DD7H
	DW Tandy_102_US_Virtual_T_1_7
	DW 0665H
	DW Tandy_200_Virtual_T_1_7
	DW 91C7H
	DW NEC_PC_8201A_Virtual_T_1_7
	DW D4BAH
	DW NEC_PC_8300_Virtual_T_1_7
	DW B753H
	DW Olivetti_M10_Europe_Virtual_T_1_7
	DW 0000H
	DW ROM_NOT_RECOGNIZED
Kyocera_Kyotronic_85:                    DB "Kyocera Kyotronic 85",0
Kyocera_Kyotronic_85_Virtual_T_1_7_no_Y2K: DB "Kyocera Kyotronic 85 (Virtual T 1.7, no Y2K)",0
Kyocera_Kyotronic_85_y2k:                DB "Kyocera Kyotronic 85.y2k",0
M10_System_ROM_EU:                       DB "M10 System ROM EU",0
M10_System_ROM_EU_y2k:                   DB "M10 System ROM EU.y2k",0
M10_System_ROM_NorthAmerica:             DB "M10 System ROM NorthAmerica",0
M10_System_ROM_NorthAmerica_y2k:         DB "M10 System ROM NorthAmerica.y2k",0
NEC_PC_8201A:                            DB "NEC PC-8201A",0
NEC_PC_8201A_Virtual_T_1_7:              DB "NEC PC-8201A (Virtual-T 1.7)",0
NEC_PC_8201A_y2k:                        DB "NEC PC-8201A.y2k",0
NEC_PC_8300:                             DB "NEC PC-8300",0
NEC_PC_8300_Beckman_E3_2:                DB "NEC PC-8300 Beckman-E3.2",0
NEC_PC_8300_Virtual_T_1_7:               DB "NEC PC-8300 (Virtual-T 1.7)",0
NEC_PC_8300_y2k:                         DB "NEC PC-8300.y2k",0
Olivetti_M10_Europe_Virtual_T_1_7:       DB "Olivetti M10 (Europe) (Virtual-T 1.7)",0
TRS_80_Model_100:                        DB "TRS-80 Model 100",0
TRS_80_Model_100_Virtual_T_1_7:          DB "TRS-80 Model 100 (Virtual-T 1.7)",0
TRS_80_Model_100_y2k:                    DB "TRS-80 Model 100.y2k",0
Tandy_102_US_Virtual_T_1_7:              DB "Tandy 102 (US) (Virtual-T 1.7)",0
Tandy_102_uk:                            DB "Tandy 102.uk",0
Tandy_102_uk_y2k:                        DB "Tandy 102.uk.y2k",0
Tandy_102_us:                            DB "Tandy 102.us",0
Tandy_102_us_y2k:                        DB "Tandy 102.us.y2k",0
Tandy_200_M13:                           DB "Tandy 200.M13",0
Tandy_200_M14:                           DB "Tandy 200.M14",0
Tandy_200_M15:                           DB "Tandy 200.M15",0
Tandy_200_M15_y2k:                       DB "Tandy 200.M15.y2k",0
Tandy_200_Virtual_T_1_7:                 DB "Tandy 200 (Virtual-T 1.7)",0
Tandy_200_us:                            DB "Tandy 200.us",0
Tandy_600_BASIC:                         DB "Tandy 600 BASIC",0
Televerket_Modell_100:                   DB "Televerket Modell 100",0
hd61830:                                 DB "hd61830",0
ROM_NOT_RECOGNIZED                       DB "ROM not recognized. Please report at\r\ngithub.com/hackerb9/crc16-modelt",0
