#!/bin/bash

# The machine language program has to fit between ORG and MAXRAM in
# the space reserved in RAM using CLEAR 256, _ORG_. 

# Tandy 200 has lowest MAXRAM at 61104. 
limit=$((61104))
file=${1:-CRC16.CO}
org="$2"
size=$(stat -c %s "$file")

if (( $size == 0 )); then
    echo "Error: Size of $file is zero" >&2
    exit 1
fi

if [ -z "$org" ]; then
    org=$( od -d -N2 "$file" | head -1 | cut -d ' ' -f2 )
#    echo "ORG is $org"
fi

endaddr=$(( size + org ))
if (( endaddr > limit )); then
    echo "Error for $file!" >&2 
    echo -e "\tORG + filesize exceeds maxram limits by $((endaddr-limit)) bytes!" >&2 
    echo -e "\t$org + $size = $endaddr > $limit (MAXRAM of T200)." >&2 
    exit 1
fi
